name: Mac builds

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-10.15
    strategy:
      matrix:
        cxx:
          - g++-9
          - clang++
        build_type: [Debug, Release]
        std: [14]

    steps:
    - uses: actions/checkout@v2

    - name: Configure build
      working-directory: ${{runner.workspace}}
      env:
        CXX: ${{matrix.cxx}}
        CXXFLAGS: ${{matrix.cxxflags}}
      # Note: $GITHUB_WORKSPACE is distinct from ${{runner.workspace}}.
      #       This is important
      run: |
        cmake -Bbuild -H$GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
              -DCMAKE_CXX_STANDARD=${{matrix.std}} -DCATCH_DEVELOPMENT_BUILD=ON

    - name: Build tests + lib
      working-directory: ${{runner.workspace}}/build
      run: make -j 2

    - name: Run tests
      env:
          CTEST_OUTPUT_ON_FAILURE: 1
      working-directory: ${{runner.workspace}}/build
      # Hardcode 2 cores we know are there
      run: ctest -C ${{matrix.build_type}} -j 2
